### ISSUE TITLE
Rewards on shared coinbase get assigned to first smesher id only

### ISSUE THREAD

**Issue by schinzelh** [spacemeshos/explorer-frontend#202] opened 2023-08-14 14:58 UTC
It appears that all rewards that got paid to a shared coinbase get assigned to the first smesher id seen. Prime example is

https://explorer.spacemesh.io/smeshers/0x4fc930cf21ac3f2431991a3c4fea4bea580e2d9752928c496fa7aa8d8bf2c1d1

which uses coinbase sm1qqqqqqzmt7dcrfccd4n3c76q3jfnnx0fj8uuy7q22laey

According to explorer this 1.5 TiB smesher got SMH 37k+ so far, while all other (100+) smeshers using the same coinbase got nothing - which is not the case of course.

<img width="1057" alt="image" src="https://github.com/spacemeshos/explorer-frontend/assets/636669/633808a8-e4c8-4413-b1cf-4f407c106437">

**Comment by lrettig** [comment] 2023-09-25 20:41
Duplicate of #189

**Closed by lrettig** 2023-09-25 20:41 UTC
